// <auto-generated />
using System;
using FacturasAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturasAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FacturasAPI.Models.Entities.Factura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Correlativo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Monto")
                        .IsRequired()
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("FacturasAPI.Models.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Correlativo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("FacturaId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Monto")
                        .IsRequired()
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("items");
                });

            modelBuilder.Entity("FacturasAPI.Models.Entities.Item", b =>
                {
                    b.HasOne("FacturasAPI.Models.Entities.Factura", null)
                        .WithMany("Items")
                        .HasForeignKey("FacturaId");
                });

            modelBuilder.Entity("FacturasAPI.Models.Entities.Factura", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
